services:
  nginx:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
  portal:
    image: ricardoalcantara/openpasswd-portal:latest
  console:
    image: ricardoalcantara/openpasswd-console:latest
    environment:
      - OPENPASSWD_SERVER=//api.openpasswd.com
  api:
    image: ricardoalcantara/openpasswd-server:latest
    depends_on:
      - postgres
    env_file:
      - openpasswd-server/.env
  postgres:
    image: postgres:14
    env_file:
      - postgres/.env
      
      